def fun1():
    try:
        print("In the try block")
        raise "Exception"
    except 
